# Generated by Django 3.2.9 on 2021-11-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
