# Generated by Django 3.2.9 on 2021-11-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211113_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='', max_length=1),
        ),
    ]
