# Generated by Django 3.2.9 on 2021-11-17 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_publicuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicuser',
            name='likes',
            field=models.ManyToManyField(related_name='_accounts_publicuser_likes_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
