# Generated by Django 3.2.9 on 2021-11-17 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_publicuser_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='_accounts_publicuser_likes_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
